name: ServerChan Notification
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send WeChat Notification
      run: curl "https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=GitHub仓库更新提醒"
