name: ServerChan Notification
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send WeChat Notification
        uses: zidingyi007/actions-serverchan@master
        with:
          sckey: ${{ secrets.SCKEY }}
          text: "您的serverchan-test仓库有新推送"
