name: ServerChan-Notify
on:
push:
branches: [ main ]
jobs:
wechat-notify:
runs-on: ubuntu-latest
steps:
- name: Send WeChat Message
uses: niltok/serverchan-action@v1
with:
sckey: ${{ secrets.SCKEY }}
text: "仓库更新提醒"
desp: "您的serverchan-test仓库有新推送"
